{{- if .Values.configMap.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "raftkv.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "raftkv.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
