{{- if .Values.raftkv.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "raftkv.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "raftkv.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ include "raftkv.jwtSecret" . | b64enc | quote }}
  admin-password: {{ include "raftkv.adminPassword" . | b64enc | quote }}
{{- end }}
